databases:
  - name: geldspar
    databaseName: geldspar
    user: geldspar_user

services:
  - type: web
    name: GeldSpar
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: geldspar
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false